/*
    AUTO-GENERATED TINYSOUNDFONT INTERNAL WRAPPER FUNCTIONS
    This file is automatically generated by gen_csharp.py
    DO NOT EDIT MANUALLY

    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead.
*/

#ifndef TSF_CSHARP_INTERNAL_WRAPPERS_H
#define TSF_CSHARP_INTERNAL_WRAPPERS_H

#include "tsf.h"
#include "tml.h"

// For Emscripten builds, these functions need to be exported
#ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #define TSF_EXPORT EMSCRIPTEN_KEEPALIVE
#else
    #define TSF_EXPORT
#endif

#endif // TSF_CSHARP_INTERNAL_WRAPPERS_H
